server:
  port: 9090
  
spring:
  application:
    name: IoT compas
    
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: test
    url: jdbc:mysql://localhost:3306/IOT
    username: root
    
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
